services:
  database:
    image: postgres:16-alpine
    container_name: mobile-desk-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - mobile_desk_data:/var/lib/postgresql/data

volumes:
  mobile_desk_data:
